### ISSUE TITLE
%Z in strptime doesn't match EST affecting "Trending" feed

### ISSUE THREAD

**Issue by siuside** [awaters1/plugin.video.espn_3#25]
`22:02:01 T:8436 ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<-- - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS! Error Type: <type 'exceptions.ValueError'> Error Contents: time data u'2016-06-08T21:00:00EDT' does not match format '%Y-%m-%dT%H:%M:%S%Z' Traceback (most recent call last): File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.espn_3\addon.py", line 246, in <module> getattr(class_def(), method_name)(args) File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.espn_3\resources\lib\register_mode.py", line 8, in new_function original_function(*args, **kwargs) File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.espn_3\resources\lib\appletv.py", line 149, in trending_mode index_listing(listing) File "C:\Users\htpc\AppData\Roaming\Kodi\addons\plugin.video.espn_3\resources\lib\addon_util.py", line 203, in index_listing starttime = time.strptime(listing['startTime'], time_format) File "C:\Program Files (x86)\Kodi\system\python\Lib\_strptime.py", line 467, in _strptime_time return _strptime(data_string, format)[0] File "C:\Program Files (x86)\Kodi\system\python\Lib\_strptime.py", line 325, in _strptime (data_string, format)) ValueError: time data u'2016-06-08T21:00:00EDT' does not match format '%Y-%m-%dT%H:%M:%S%Z' -->End of Python script error report<-- 22:02:01 T:8100 ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.espn_3/?MODE=%2fappletv%2ftrending 22:02:01 T:8100 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.espn_3/?MODE=%2fappletv%2ftrending) failed`

Per @awaters1 bug in python  http://bugs.python.org/issue22377

Workaround in 73ed038d14747faa7e1939823a82188f5e4ccabb tested and worked successfully.

**Comment by siuside** [comment]
Closing per 73ed038d14747faa7e1939823a82188f5e4ccabb
