### ISSUE TITLE
UnboundLocalError: local variable 'data_tree' referenced before assignment

### ISSUE THREAD

**Issue by millic** [awaters1/plugin.video.espn_3#29]
With the latest version 2.9.2 the addon fails to start and the log shows the following error:

`18:34:13 T:123145303453696   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnboundLocalError'>
                                            Error Contents: local variable 'data_tree' referenced before assignment
                                            Traceback (most recent call last):
                                              File "/Users//Library/Application Support/Kodi/addons/plugin.video.espn_3-master/addon.py", line 263, in <module>
                                                ROOT_ITEM(refresh)
                                              File "/Users//Library/Application Support/Kodi/addons/plugin.video.espn_3-master/addon.py", line 35, in ROOT_ITEM
                                                channel_list = events.get_channel_list(include_premium)
                                              File "/Users//Library/Application Support/Kodi/addons/plugin.video.espn_3-master/resources/lib/events.py", line 5, in get_channel_list
                                                networks = player_config.get_networks()
                                              File "/Users//Library/Application Support/Kodi/addons/plugin.video.espn_3-master/resources/lib/player_config.py", line 45, in get_networks
                                                networks = get_config_soup().findall('.//network')
                                              File "/Users//Library/Application Support/Kodi/addons/plugin.video.espn_3-master/resources/lib/player_config.py", line 24, in get_config_soup
                                                return util.get_url_as_xml_soup_cache(PLAYER_CONFIG_URL, PLAYER_CONFIG_FILE, TIME_DIFFERENCE)
                                              File "/Users//Library/Application Support/Kodi/addons/plugin.video.espn_3-master/resources/lib/util.py", line 43, in get_url_as_xml_soup_cache
                                                return load_element_tree(xml_data)
                                              File "/Users//Library/Application Support/Kodi/addons/plugin.video.espn_3-master/resources/lib/util.py", line 69, in load_element_tree
                                                return data_tree
                                            UnboundLocalError: local variable 'data_tree' referenced before assignment
                                            -->End of Python script error report<--`

**Comment by awaters1** [comment]
Should be fixed with https://github.com/kodi-addons/plugin.video.espn_3/commit/78c7ab241c5c62f17d9f383f37ff279e47f4a5bb
